### ISSUE TITLE
Set Double Ports at instance start. Server dont Show Up in LAN 

### ISSUE THREAD

**Issue by St4rmie** [Zerschranzer/Ark-Survival-ascended-dedicated-server-without-docker#2] opened 2024-12-11 15:27 UTC
Hello,

I installed a fresh Debian system and set up this script on it. When I try to start an instance, everything runs without any issues. However, the server is not accessible locally. All ports are open. I then checked the logs and configs and noticed that when starting, the script adds the ports stored in the instance config to the normal ARK server parameters.

I couldn't resolve this issue, so I worked around it. I manually removed the variables from the script and manually set the ports to 27015 and 7777. Htop now shows the correct start parameters. However, the server still cannot be found on the LAN.

**Comment by UncensoredCobra** [comment] 2024-12-14 13:33
i also have this issue can please explain how you fixed more indepth im a huge newb when it comes to this?

**Comment by Zerschranzer** [comment] 2024-12-14 17:35
The ports are configured exclusively in the file `/instances/<yourinstance>/instance_config.ini`. When you start an instance, the `instance_config.ini` is read and added to the start parameters. This then overwrites the `GameUserSettings.ini`. I don't fully understand what the issue is. Of course, you need to configure different ports for each instance in the specific `instance_config.ini` for each instance.

**Comment by Zerschranzer** [comment] 2024-12-14 19:26
If you want to connect to the server locally, you can try connecting via the console. Start a local game, open the console, and enter:  
`open <IP-Address>:<Port>`  

If your server has a password, the syntax would look like this:  
`open <IP-Address>:<Port>?password=<Server-Password>`  

For example:  
`open 127.0.0.1:7777?password=mysecretpassword`  

It’s completely normal that the server doesn’t show up in the server list. This is because the server registers with the Steam master server, which requires the correct ports to be open.

**Comment by Zerschranzer** [comment] 2024-12-15 01:14
I’ve reviewed and updated the script to address the issue of conflicting port configurations. The new version includes a mechanism to **detect duplicate port entries** across all instances. If duplicate ports are found in the `instance_config.ini` files, the script will **prevent the server from starting** and display a clear error message highlighting the conflicting instances and ports.

### What’s new:
- **Duplicate Port Check**: Before starting any instance, the script now checks the `Port`, `QueryPort`, and `RCONPort` entries across all instances. If a conflict is detected, the script will:
  1. Identify the conflicting ports and the respective instances.
  2. Provide detailed feedback so you can resolve the issue in the respective `instance_config.ini` files.

- **Error Prevention**: Servers will not start if duplicate ports are found, preventing unpredictable behavior and conflicts.

### What to do:
1. Update your script to the latest version.
2. Ensure that each instance has unique ports configured in its `instance_config.ini` file:
   ```bash
   ./ark_instance_manager.sh
   > Manage Instance > [Your Instance] > Edit Configuration > Instance Configuration
   ```
3. After resolving any conflicts, restart your instances.

This update should eliminate issues related to conflicting port configurations.

**Comment by UncensoredCobra** [comment] 2024-12-15 01:32
Thank you so much I really appreciate it and what I was thinking is it's because you have it search for the context of the port but for game port you only have it search for "port=" but technically "RconPort=" still has Rcon"Port=" in it was this also maybe the issue I have never coded in python was just trying to help

**Comment by UncensoredCobra** [comment] 2024-12-15 01:35
Because in my mind if python is not smart it will just use anything that has Port= in it as the selection and that's why you get all your ports for rcon and Query and game port show up at the port section

**Comment by Zerschranzer** [comment] 2024-12-15 01:42
The script is written in Bash, not Python. The check_for_duplicate_ports function explicitly searches for ^Port=, ^RCONPort=, and ^QueryPort= in the instance_config.ini. Each port type is processed separately, so RCONPort= can't be misinterpreted as Port=. If issues persist, they are likely due to misconfigured or duplicate entries in the instance_config.ini files.

**Comment by UncensoredCobra** [comment] 2024-12-15 01:58
Ok thank you so much I will try it out as soon as I can and let you know because I really like it!

**Comment by UncensoredCobra** [comment] 2024-12-15 08:32
i am still having this issue here is the log file from the Shootergame/saved/logs/shootergame.log it cleary shows the ports being messed up
[ShooterGame.log](https://github.com/user-attachments/files/18139454/ShooterGame.log)

**Comment by Zerschranzer** [comment] 2024-12-15 09:01
check your instance_config.ini for unique and correct port definitions.
Also, ensure that no conflicting ports are set in the GameUserSettings.ini.
If possible, share your instance_config.ini and the full startup parameters
so I can better understand the issue.

UncensoredCobra ***@***.***> schrieb am So., 15. Dez. 2024,
09:32:

**Comment by Zerschranzer** [comment] 2024-12-15 12:28
I tried to reproduce your issue in Debian, Ubuntu, Arch, and Fedora containers, all installed with the minimal possible setup. I cannot replicate your issue on any of these operating systems. The problem must lie in your Linux system configuration, your instance_config.ini, or your GameUserSettings.ini. As a test, try downloading the ARK Server Manager script into a different folder (e.g., /home/yourusername/asatest) and install everything from scratch with the default configurations. Then, gradually apply the configuration changes you want. If an error occurs at any step, let me know at which step it happens so we can pinpoint what went wrong.

**Comment by UncensoredCobra** [comment] 2024-12-16 12:12
i am dumb and i was using a port check tool that doesnt check udp type of ports only tcp also you should specify you have to use a command in the in game console to connect to the server locally. 

How To Connect to a Ark Server Hosted on the Same network 

1.make sure the server is started also use https://www.ipvoid.com/udp-port-scan/ to scan port 7777 
2.boot up ark on your gaming pc 
3.hit the tilda key to open console EX. ` (if this doesnt work look in you keybinds for the console key bind)
4.now type 'open ip:port' 
5.you should join and everything should be working 

Cheers im very sorry for being dumb and having you do all that becasue idek maybe it was me all alone i hope you have a goodnight man/woman/'enter pronoun here'

**Comment by Zerschranzer** [comment] 2024-12-17 00:27
I tried to reproduce your issue in a **Debian 12 Docker container**, but I had no problems – the server worked perfectly.

Here’s what I did:

1. I started a fresh Debian container with the following command:
   ```bash
   docker run -it --name ark-test \
       --network bridge \
       -p 7777:7777/udp -p 27015:27015/udp -p 27020:27020/tcp \
       debian:12 bash
   ```

2. I downloaded the script, installed the server, and created an instance using your provided configuration. The server started successfully.

3. I launched the ARK client and connected to the server using the console command:
   ```bash
   open <my_ip>
   ```
   The connection worked without any issues.

---

### Observations:
Your `htop` output appears correct. The way Proton interprets and displays the start parameters can cause duplicate entries. However, this **does not affect** the functionality of the server. The ports specified in your `instance_config.ini` are correctly applied.

---

### Suggested Solutions:
1. **Ensure the server binds to all IP addresses**:  
   Add the following to your `instance_config.ini` under `CustomStartParameters`:
   ```bash
   -MULTIHOME=0.0.0.0
   ```

2. **Firewall/iptables configuration**:  
   Even though your firewall is disabled, is `iptables` correctly set up? Double-check.

3. **Check active ports**:  
   While the server is running, verify which ports are listening using:
   ```bash
   lsof -i -P -n | grep -E '7777|27015|27020'
   ```

4. **Find your actual IP address**:  
   Use the following command to determine your current IP:
   ```bash
   ip a
   ```
   Then launch the ARK client, open the console, and connect using:
   ```bash
   open <your_ip>
   ```

5. **Check server logs**:  
   Inspect the log file for any errors:
   ```bash
   /server-files/ShooterGame/Saved/Logs/ShooterGame.log
   ```

6. **Manually start the server without the script**:  
   Use the following commands to manually start the server and rule out issues with the script:

   ```bash
   export STEAM_COMPAT_DATA_PATH="/path/to/server-files/steamapps/compatdata/2430930"
   export STEAM_COMPAT_CLIENT_INSTALL_PATH="/path/to/GE-Proton9-5"

   "/path/to/GE-Proton9-5/proton" run "/path/to/server-files/ShooterGame/Binaries/Win64/ArkAscendedServer.exe" \
       TheIsland_WP?listen?SessionName="MyTestServer"?MaxPlayers=70?Port=7777?QueryPort=27015?RCONEnabled=True?RCONPort=27020?AltSaveDirectoryName="TestInstance" \
       -MULTIHOME=0.0.0.0 -NoBattlEye -crossplay -server -log
   ```

---

### Final Thoughts:
Since I was unable to reproduce your problem, I strongly suspect there is a **misconfiguration in your Debian environment**. Please follow the steps above to isolate and resolve the issue.

Let me know how it goes!

**Comment by ShamutikReborn** [comment] 2024-12-19 13:23
Hello! I encountered a problem specifying ports. In the GameUserSettings.ini file, why is port 49000 the same as the rcon port, but another port should be specified there. Or am I misunderstanding something?
![Снимок экрана 2024-12-19 211941](https://github.com/user-attachments/assets/a81d1538-0eab-47e4-9277-56f7a08646a0)
![Снимок экрана 2024-12-19 212016](https://github.com/user-attachments/assets/7505a960-9be9-41cc-9e4c-d2802fb29a40)

**Comment by Zerschranzer** [comment] 2024-12-19 17:17
> Hello! I encountered a problem specifying ports. In the GameUserSettings.ini file, why is port 49000 the same as the rcon port, but another port should be specified there. Or am I misunderstanding something?)

Let me address your concern regarding the ports in your **GameUserSettings.ini** file.

### **1. Default or Migrated GameUserSettings?**
Could you confirm if the **GameUserSettings.ini** file is:
- The default file created by the server on first start, or
- A file you copied or migrated from an old server?

The entry you shared:  
```plaintext
ServerAdminPassword=********QueryPort=27014?Port=49000
```
This format is **not correct** for the **GameUserSettings.ini** file. This might indicate it was modified incorrectly or inherited from another setup.

---

### **2. Role of `instance_config.ini`**
The `instance_config.ini` file in this server manager only contains the **start parameters** used to launch the server. These parameters (like ports) will always override any settings defined in the **GameUserSettings.ini** file when the server starts.

In other words:
- Even if **port settings** exist in `GameUserSettings.ini`, they will be ignored.
- The settings from `instance_config.ini` will take precedence and be applied at runtime.

---

### **3. GameUserSettings.ini Issues**
From the snippet you shared, the **GameUserSettings.ini** file appears to have a formatting issue. Specifically:
- Multiple unrelated parameters are combined into one line (`ServerAdminPassword=...QueryPort=...Port=...`).
- This format is invalid and could lead to undefined behavior.

**Solution**:  
- Backup the file if you want to save important settings like custom game configurations.
- Delete the existing **GameUserSettings.ini** file.
- Restart the server. This will generate a fresh, properly formatted file.

Once the file is recreated, you can reapply your custom settings.

---

### **Clarification for All Users**
Based on multiple questions regarding ports, I’ve noticed that this is a source of confusion for some users. I will make this behavior more explicitly clear in the README in future updates, to help avoid misunderstandings.

**Comment by ShamutikReborn** [comment] 2024-12-20 01:02
GameUserSettings is a default file created when the server starts. I tried deleting it and it still creates in the wrong format.
I tested this on Ubuntu and Debian VMs, as well as in LXC containers. And I encounter the described problem everywhere.

Each VM had a clean installation and then your script was launched, the necessary applications were downloaded, an instance was created and then the server was launched to create GameUserSettings

**Comment by Zerschranzer** [comment] 2024-12-20 22:42
> GameUserSettings is a default file created when the server starts. I tried deleting it and it still creates in the wrong format. I tested this on Ubuntu and Debian VMs, as well as in LXC containers. And I encounter the described problem everywhere.
> 
> Each VM had a clean installation and then your script was launched, the necessary applications were downloaded, an instance was created and then the server was launched to create GameUserSettings

I was able to reproduce the issue that caused the incorrect entry in the `GameUserSettings.ini`. The problem occurred due to a conflict in the script when the instance name was identical to the server name. This conflict led to the server misbehaving and creating the faulty entry in the `GameUserSettings.ini`.

To resolve this, I adjusted the script by appending a trailing space to the `ServerName`. This ensures that even if the instance name matches the server name, they are treated as distinct values internally. The trailing space is invisible to users and does not affect the server's visibility or functionality.

With this fix, the issue should no longer occur, and the `GameUserSettings.ini` will now be generated correctly. 
If you encounter further issues, please let me know.

**Comment by Zerschranzer** [comment] 2024-12-23 23:26
I just wanted to follow up regarding the issue. Has the fix resolved the problem for you, or are you still encountering any related issues? If everything is working as expected now, I would like to close this issue.

**Closed** 2024-12-27 13:20 UTC
